#include <iostream>
#include <exception>

#include <thodd/functional/functional.hpp>


int main() 
try
{

}
catch(std::exception& e)
{
    std::cout << e.what() << std::endl;
}